# -*- coding: utf-8 -*-
"""
100 Finnish test queries representing what a doctor might search from
medical literature while seeing patients in clinic.

Length deliberately varies from a single word (e.g. a drug or condition name)
to full natural-language clinical questions, in roughly increasing order.
"""

QUERIES = [
    # --- Single words: conditions, drugs, symptoms, lab terms (1 word) ---
    "eteisvärinä",
    "keuhkokuume",
    "migreeni",
    "anemia",
    "metformiini",
    "sepsis",
    "astma",
    "nivelreuma",
    "sydäninfarkti",
    "aivoinfarkti",
    "kihti",
    "osteoporoosi",
    "haimatulehdus",
    "munuaiskivi",
    "verenpainetauti",
    "keuhkoembolia",
    "kilpirauhasen vajaatoiminta",
    "tyypin 2 diabetes",
    "krooninen munuaisten vajaatoiminta",
    "sydämen vajaatoiminta",

    # --- Short phrases (3-5 words) ---
    "korkean verenpaineen lääkehoito",
    "diabeteksen ensisijainen lääkitys",
    "rintakivun erotusdiagnoosi",
    "antibiootti virtsatietulehdukseen",
    "varfariinin ja antibioottien yhteisvaikutukset",
    "statiinien haittavaikutukset lihaksiin",
    "eteisvärinän antikoagulaatiohoito",
    "akuutin astmakohtauksen hoito",
    "anemian syyt iäkkäällä potilaalla",
    "metformiinin vasta-aiheet munuaisten vajaatoiminnassa",
    "kohonneen kaliumin hoito",
    "migreenin estolääkitys",
    "kortikosteroidien pitkäaikaiskäytön riskit",
    "syvän laskimotukoksen diagnostiikka",
    "raudanpuuteanemian hoito raskauden aikana",
    "kilpirauhasarvojen tulkinta",
    "CRP-arvon merkitys infektiossa",
    "ibuprofeenin annostus aikuiselle",
    "penisilliiniallergian ristireaktiot",
    "verenohennuslääkkeen tauotus ennen leikkausta",

    # --- Medium clinical questions (6-10 words) ---
    "Mikä on tyypin 2 diabeteksen ensisijainen lääkehoito?",
    "Milloin aloittaa antikoagulaatio eteisvärinässä?",
    "Kuinka tulkita kohonnut troponiiniarvo ilman rintakipua?",
    "Mitkä ovat keuhkoembolian tyypilliset oireet ja löydökset?",
    "Mikä on suositeltu verenpainetavoite diabeetikolla?",
    "Kuinka erottaa virusperäinen ja bakteeriperäinen nielutulehdus?",
    "Mitä laboratoriokokeita tarvitaan väsymyksen selvittelyssä?",
    "Milloin lähettää potilas päivystykseen rintakivun vuoksi?",
    "Mikä on metformiinin tavanomainen aloitusannos aikuisella?",
    "Kuinka hoitaa akuuttia kihtikohtausta munuaisten vajaatoiminnassa?",
    "Mitkä lääkkeet voivat aiheuttaa pitkän QT-ajan?",
    "Mikä on D-dimeerin merkitys laskimotukoksen poissulkemisessa?",
    "Kuinka annostella enoksapariinia munuaisten vajaatoiminnassa?",
    "Mitä rokotuksia suositellaan iäkkäälle keuhkoahtaumapotilaalle?",
    "Milloin antibioottihoito on aiheellinen poskiontelotulehduksessa?",
    "Mikä on suositeltu kalium- ja kreatiniiniseuranta ACE-estäjähoidossa?",
    "Kuinka tunnistaa sepsis varhaisessa vaiheessa päivystyksessä?",
    "Mitkä ovat tyypin 1 ja tyypin 2 diabeteksen erot?",
    "Mikä on oikea INR-tavoite varfariinihoidossa eteisvärinässä?",
    "Kuinka hoidetaan lievää masennusta perusterveydenhuollossa?",

    # --- Full natural-language sentences / case vignettes (10+ words) ---
    "65-vuotiaalla potilaalla on äkillinen rintakipu ja hengenahdistus, mitkä ovat todennäköisimmät syyt?",
    "Naispotilaalla on toistuvia virtsatietulehduksia, milloin tarvitaan tarkempia tutkimuksia tai profylaksia?",
    "Diabeetikon HbA1c on 9 prosenttia metformiinista huolimatta, mikä lääke kannattaa lisätä seuraavaksi?",
    "Iäkäs potilas kaatuilee toistuvasti kotona, mitä syitä tulisi selvittää ja miten kaatumisia ehkäistään?",
    "Potilaalla on krooninen yskä yli kahdeksan viikkoa ilman tupakointia, mitä erotusdiagnooseja tulee harkita?",
    "Kuinka säätää verenpainelääkitystä raskaana olevalla potilaalla, jolla todetaan kohonnut verenpaine?",
    "Milloin statiinihoito tulisi aloittaa potilaalla, jolla ei ole aiempaa sydäntapahtumaa mutta korkea riski?",
    "Potilaalla on kohonnut maksa-arvo rutiinikokeissa ilman oireita, miten jatkoselvittely kannattaa tehdä?",
    "Mitä tukoksenestohoitoa suositellaan potilaalle, jolla on eteisvärinä ja aiempi maha-suolikanavan verenvuoto?",
    "Nuorella aikuisella on toistuvia päänsärkykohtauksia ja näköhäiriöitä, milloin tarvitaan aivojen kuvantaminen?",
    "Kuinka hoidetaan yhteisön hankkimaa keuhkokuumetta avohoidossa olevalla aiemmin terveellä aikuisella?",
    "Potilaalla on tyypin 2 diabetes ja munuaisten vajaatoiminta, mitkä diabeteslääkkeet ovat tällöin turvallisia?",
    "Mitä tutkimuksia ja hoitoa tarvitaan potilaalle, jolla epäillään syvää laskimotukosta alaraajassa?",
    "Kuinka arvioida ja hoitaa hyponatremiaa iäkkäällä potilaalla, joka käyttää diureetteja ja masennuslääkkeitä?",
    "Potilas käyttää varfariinia ja tarvitsee antibioottikuurin, mitä yhteisvaikutuksia ja seurantaa on huomioitava?",
    "Milloin keuhkoahtaumataudin pahenemisvaiheessa tulee harkita antibioottia ja systeemistä kortikosteroidia?",
    "Kuinka tunnistaa ja hoitaa anafylaktinen reaktio potilaalla, jolle on juuri annettu uusi lääke vastaanotolla?",
    "Mitä elintapaohjeita ja lääkehoitoa suositellaan potilaalle, jolla on äskettäin todettu kohonnut kolesteroli?",
    "Potilaalla on rasitukseen liittyvää rintakipua mutta normaali lepo-EKG, mitä jatkotutkimuksia tarvitaan?",
    "Kuinka erotetaan toiminnallinen vatsavaiva ja vakavampi sairaus potilaalla, jolla on pitkittyneitä vatsaoireita?",
    "Mitkä ovat keskeiset varoitusmerkit, joiden vuoksi päänsärkypotilas tulee lähettää välittömästi jatkotutkimuksiin?",
    "Kuinka hoitaa kivuliasta vyöruusua iäkkäällä potilaalla ja miten ehkäistä postherpeettistä neuralgiaa?",
    "Potilaalla on uniapneaepäily, mitkä oireet ja löydökset tukevat diagnoosia ja milloin tarvitaan unitutkimus?",
    "Mitä huomioida aloitettaessa SGLT2-estäjä sydämen vajaatoimintaa sairastavalle diabeetikolle?",
    "Kuinka arvioida murtumariskiä ja milloin aloittaa luulääkitys postmenopausaalisella naisella?",
    "Potilaalla on toistuvia matalan verensokerin tuntemuksia ilman diabetesta, mitä syitä tulee selvittää?",
    "Milloin kohonnut verenpaine vastaanotolla edellyttää kotimittauksia tai vuorokausirekisteröintiä ennen lääkitystä?",
    "Kuinka hoitaa raudanpuuteanemiaa potilaalla, joka ei siedä suun kautta otettavia rautavalmisteita?",
    "Mitä tutkimuksia tarvitaan, kun nuorella naisella epäillään kilpirauhasen liikatoimintaa väsymyksen ja sydämentykytysten vuoksi?",
    "Kuinka säätää insuliiniannostusta sairauspäivinä tyypin 1 diabetesta sairastavalla potilaalla?",
    "Potilaalla on krooninen alaselkäkipu ilman hälyttäviä oireita, mitä hoitoa ja kuvantamista suositellaan ensilinjassa?",
    "Mitä lääkkeiden yhteisvaikutuksia tulee tarkistaa, kun monilääkitylle iäkkäälle potilaalle lisätään uusi valmiste?",
    "Kuinka tunnistaa aivoverenkierron häiriö nopeasti ja mitkä ovat liuotushoidon aikaikkunan keskeiset kriteerit?",
    "Potilaalla on kuumetta ja niskajäykkyyttä, mitkä löydökset viittaavat bakteeriperäiseen aivokalvontulehdukseen?",
    "Milloin nivelkivun yhteydessä tulee epäillä septistä artriittia ja miten se varmistetaan päivystyksessä?",
    "Kuinka hoidetaan akuuttia eteisvärinää potilaalla, jolla on nopea kammiovaste mutta vakaa verenkierto?",
    "Mitä seurantaa ja varotoimia tarvitaan aloitettaessa metotreksaattihoito nivelreumaa sairastavalle potilaalle?",
    "Potilaalla on turvotusta jaloissa ja hengenahdistusta rasituksessa, mitkä tutkimukset auttavat erottamaan sydän- ja keuhkoperäisen syyn?",
    "Kuinka arvioida itsemurhariskiä ja milloin ohjata masentunut potilas kiireellisesti psykiatriseen arvioon?",
    "Mitä elintapamuutoksia ja lääkehoitoa suositellaan potilaalle, jolla on metabolinen oireyhtymä ja rasvamaksa?",
]

assert len(QUERIES) == 100, f"Expected 100 queries, got {len(QUERIES)}"
